=== Raul-Melgosa/Reto-Consultoria-ESports-Equipo3/Fase2/XSDClasificacion.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="clasificacion" type="tipoClasificacion"/>
  
  <xs:complexType name="tipoClasificacion">
    <xs:sequence>
      <xs:element name="equipo" maxOccurs="unbounded" type="tipoEquipo"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="tipoEquipo">
    <xs:sequence>
      <xs:element name="ID_EQUIPO" type="xs:int"/>
      <xs:element name="PUNTOS" type="xs:int"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== Raul-Melgosa/Reto-Consultoria-ESports-Equipo3/Fase2/XML/clasificacionSQL.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE clasificacion SYSTEM "DTDClasificacion.dtd">-->
<clasificacion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XSDClasificacion.xsd">
 <equipo>
  <ID_EQUIPO>1</ID_EQUIPO>
  <PUNTOS>6</PUNTOS>
 </equipo>
 <equipo>
  <ID_EQUIPO>4</ID_EQUIPO>
  <PUNTOS>6</PUNTOS>
 </equipo>
 <equipo>
  <ID_EQUIPO>3</ID_EQUIPO>
  <PUNTOS>0</PUNTOS>
 </equipo>
 <equipo>
  <ID_EQUIPO>2</ID_EQUIPO>
  <PUNTOS>0</PUNTOS>
 </equipo>
</clasificacion>
